services:
    galandas.contodb.listener:
        class: galandas\contodb\event\listener
        arguments:
            - '@template'
            - '@config'         
        tags:
            - { name: event.listener }
